hmcts/sscs-ccd-e2e-tests

e2e/features/alternate-happy-path.feature
e2e/features/data/scanned-case.js
e2e/features/happy-path.feature
e2e/features/interloc-review.feature
e2e/features/lapse-case.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/interloc-review.steps.ts
e2e/features/step_definitions/lapse-case.steps.ts
e2e/features/step_definitions/response-reviewed.steps.ts
e2e/features/step_definitions/withdrawal.steps.ts
e2e/features/withdrawal.feature
e2e/helpers/ni-generator.ts
e2e/pages/any-ccd.page.ts
e2e/pages/dwpresponse.page.ts
e2e/service.conf.js

More scenarios are added to the test.
```
[ ] Yes
[x] No
```

UAT Scenarios A, B, D, E  and G  are completed

---

.gitignore
e2e/features.conf.js
e2e/features/alternate-happy-path.feature
e2e/features/create-bulk-scanned-appeal.feature
e2e/features/happy-path.feature
e2e/features/interloc-review.feature
e2e/features/lapse-case.feature
e2e/features/step_definitions/authentication.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/withdrawal.feature
e2e/flows/authentication.flow.ts
e2e/helpers/ni-generator.ts
e2e/pages/dwpresponse.page.ts
e2e/service.conf.js

user switching functionality added

---

e2e/cucumber.conf.js

Timeout is increased to allow functional testing to pass onJenkins

---

e2e/features/alternate-happy-path.feature
e2e/features/happy-path.feature
e2e/features/interloc-review.feature
e2e/features/lapse-case.feature
e2e/features/withdrawal.feature

Keep only 1 test active
```
[ ] Yes
[ X] No
```

Uat happy path

---

e2e/cucumber.conf.js
e2e/features.conf.js

Increase Timeout
```
[ ] Yes
[ X] No
```

Increase timeout

---

e2e/features.conf.js

Added pagetimeout"
```
[ ] Yes
[X ] No
```

Added pagetimeout

---

e2e/cucumber.conf.js

Increased Timeout
```
[ ] Yes
[ X] No
```

Increased Timeout

---

e2e/flows/authentication.flow.ts

Removed waitUntilloaded
```
[ ] Yes
[X ] No
```

Removed waitUntilloaded

---

e2e/pages/idam-sign-in.page.ts

Removed waitUntilloaded from idam-sign-in
```
[ ] Yes
[x ] No
```

Removed waitUntilloaded from idam-sign-in

---

e2e/pages/idam-sign-in.page.ts

Added waitUntilloaded back to  idam-sign-in
```
[ ] Yes
[ x] No
```

Added waitUntilloaded back to  idam-sign-in

---

e2e/flows/authentication.flow.ts

Signout and get to url
```
[ ] Yes
[x ] No
```

Signout and get to url

---

e2e/pages/idam-sign-in.page.ts

SignIn Url changed
```
[ ] Yes
[ x] No
```

SignIn Url changed

---

Jenkinsfile_nightly
e2e/cucumber.conf.js
e2e/features.conf.js
e2e/service.conf.js

Reverted timeout
```
[ ] Yes
[ x] No
```

Reverted timeout

---

e2e/cucumber.conf.js

Changed timeout
```
[ ] Yes
[ ] No
```

Changed timeout

---

e2e/features/alternate-happy-path.feature
e2e/features/create-bulk-scanned-appeal.feature
e2e/features/happy-path-user.feature
e2e/features/interloc-review.feature
e2e/features/lapse-case.feature
e2e/features/withdrawal.feature
e2e/pages/idam-sign-in.page.ts

New feature happy-path-user
```
[ ] Yes
[ x] No
```

New feature happy-path-user

---

Jenkinsfile_nightly

nightly-test added back
```
[ ] Yes
[ x] No
```

nightly-test added back

---

e2e/service.conf.js
package.json

options corrected
```
[ ] Yes
[ x] No
```

options corrected

---

Jenkinsfile_nightly
e2e/features/lapse-case.feature
e2e/service.conf.js

lapse feature added
```
[ ] Yes
[ x] No
```

lapse feature added

---

e2e/features.conf.js
e2e/features/alternate-happy-path.feature
e2e/features/happy-path.feature
e2e/features/interloc-review.feature
e2e/features/lapse-case.feature
e2e/features/withdrawal.feature
package.json

nightly-test added
```
[ ] Yes
[ x] No
```

nightly-test added

---

e2e/features/data/scanned-case.js

Corrected mrn date generation
```
[ ] Yes
[x ] No
```

Corrected mrn date generation

---

e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/pages/any-ccd.page.ts
e2e/pages/case-details.page.ts

https://tools.hmcts.net/jira/browse/SSCS-7787
Fixed - failed e2e nightly job for SSCS
```
[ ] Yes
[X] No
```

SSCS-7787-fixed nightly build on jenkins pipeline

---

e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/pages/any-ccd.page.ts
e2e/pages/case-details.page.ts

https://tools.hmcts.net/jira/browse/SSCS-7787
fixed spacing issue
```
[ ] Yes
[X] No
```

SSCS-7787-fixed the spacing issue

---

e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/pages/any-ccd.page.ts
e2e/pages/case-details.page.ts

Fix for ccd-e2e-functional tests

---

e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/pages/any-ccd.page.ts

Fix lint issues for the tests

---

e2e/features/happy-path-user.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/pages/any-ccd.page.ts

Automation test coverage for create bundle event

---

e2e/features/step_definitions/bulk-scanning.steps.ts

Fix linting issues

---

e2e/pages/idam-sign-in.page.ts

Include logs to read username

---

e2e/flows/authentication.flow.ts
e2e/pages/idam-sign-in.page.ts

Moving log line to flows folder

---

Jenkinsfile_nightly

for debug purpose removing sec key

---

Jenkinsfile_nightly
e2e/flows/authentication.flow.ts

Removed debug statements

---

Jenkinsfile_nightly
e2e/service.conf.js

add login credentials

---

Jenkinsfile_nightly
e2e/features/happy-path-user.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts

Update ccd tests to fix nightly

---

e2e/features/data/scanned-case.js
e2e/features/step_definitions/bulk-scanning.steps.ts

Increase wait time for bundle to populate

---

e2e/features/alternate-happy-path.feature
e2e/features/create-bulk-scanned-appeal.feature
e2e/features/happy-path-user.feature
e2e/features/happy-path.feature
e2e/features/interloc-review.feature
e2e/features/lapse-case.feature
e2e/features/step_definitions/lapse-case.steps.ts
e2e/features/withdrawal.feature
e2e/pages/lapsecase.page.ts
e2e/service.conf.js

https://tools.hmcts.net/jira/browse/SSCS-7993
```
[ ] Yes
[x] No
```

sscs-7993 turn on all scenarios

---

e2e/features/happy-path.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/pages/any-ccd.page.ts

add delay to flaky tests

---

Jenkinsfile_nightly
e2e/features/happy-path.feature

Added DWP user in secrets
```
[ ] Yes
[x] No
```

Sscs 7993 e2e scenarios 2

---

Jenkinsfile_nightly
e2e/cucumber.conf.js
e2e/features.conf.js
e2e/features.parallel.conf.js
e2e/features/createbundle.feature
e2e/features/data/scanned-case.js
e2e/service.conf.js
package.json
yarn.lock

Parallel test execution

---

package.json

Remove test credentials

---

package.json

Remove unused library from test framework

---

Jenkinsfile_nightly

Increase browser instance

---

Jenkinsfile_nightly
e2e/features/data/scanned-case.js
e2e/service.conf.js

Update ocr data in tests to cater new bulk scan changes

---

e2e/features/happy-path.feature
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/pages/any-ccd.page.ts

DWP user check for status

---

e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/response-reviewed.steps.ts
e2e/features/withdrawal.feature
e2e/pages/any-ccd.page.ts

Fix withdrawal for dwp
```
[ ] Yes
[x] No
```

Fix withdrawal for dwp

---

e2e/features/data/scanned-case.js
e2e/pages/any-ccd.page.ts

https://tools.hmcts.net/jira/browse/SSCS-8132
```
[ ] Yes
[x] No
```

fix telephone

---

e2e/features/data/scanned-case.js
e2e/features/issue-decision.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/issue-decision.steps.ts
e2e/pages/any-ccd-form.page.ts
e2e/pages/case-details.page.ts
e2e/pages/issue-decision.page.ts
e2e/pages/issue-direction.page.ts

https://tools.hmcts.net/jira/browse/SSCS-8132
```
[ ] Yes
[x] No
```

Sscs 8132 issue decision

---

e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/issue-decision.steps.ts
e2e/pages/any-ccd-form.page.ts
e2e/pages/case-details.page.ts
e2e/pages/issue-decision.page.ts

https://tools.hmcts.net/jira/browse/SSCS-8132
```
[ ] Yes
[x] No
```

fix style issues

---

e2e/features/step_definitions/issue-decision.steps.ts

more style

---

e2e/features/issue-decision.feature

remove issue-decision tests from nightly

---

e2e/features/issue-decision.feature
e2e/features/step_definitions/issue-decision.steps.ts
e2e/pages/case-details.page.ts

Run happy path scenarios for issue-decisions

---

e2e/features/step_definitions/action-further-evidence.steps.ts
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/pages/further-evidence.page.ts

Fix lint issues

---

e2e/features/step_definitions/action-further-evidence.steps.ts
e2e/pages/case-details.page.ts

update nightly tests

---

.gitignore
e2e/features/alternate-happy-path.feature
e2e/features/create-bulk-scanned-appeal.feature
e2e/features/createbundle.feature
e2e/features/happy-path-user.feature
e2e/features/happy-path.feature
e2e/features/interloc-review.feature
e2e/features/issue-decision-award.feature
e2e/features/issue-decision.feature
e2e/features/lapse-case.feature
e2e/features/reinstatement.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/response-reviewed.steps.ts
e2e/features/withdrawal.feature
e2e/pages/dwpresponse.page.ts
e2e/pages/response-reviewed.page.ts
yarn.lock

SSCS-8133 - DWP Response Upload for UC
Happy path for UC Dwp Upload response. See _happy-path.feature_
It seems wrong that you need to add a dispute in the upload response, the case will not go to Ready to List automatically after the dwp upload response.

SSCS-8133 - DWP Response Upload for UC

---

e2e/features/adjournment.feature
e2e/features/step_definitions/adjournment.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/pages/adjournment.page.ts

https://tools.hmcts.net/jira/browse/SSCS-8144
```
[ ] Yes
[x] No
```

Sscs 8144 adjournment tests

---

e2e/features/adjournment.feature
e2e/features/alternate-happy-path.feature
e2e/features/happy-path.feature
e2e/features/interloc-review.feature
e2e/features/issue-decision.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/withdrawal.feature

Update test steps

---

Jenkinsfile_nightly

Increase default test timeout

---

e2e/features/createbundle.feature

ignore bundle tests

---

e2e/features/happy-path.feature

Fix ccd build test

---

e2e/features/issue-decision.feature

remove decision tests from nightly test suite

---

e2e/features/adjournment.feature

Rename the "Adjourn case" event to 'Write adjournment notice'

SSCS-8347 - Rename Adjourn case event

---

e2e/features.parallel.conf.js
e2e/features/adjournment.feature
e2e/features/createbundle.feature
e2e/features/reinstatement.feature
e2e/features/step_definitions/action-further-evidence.steps.ts
package.json
yarn.lock

Add re-run logic for failed tests and enable new features

---

e2e/features/create-bulk-scanned-appeal.feature
e2e/features/esa-decision-notices.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/esa-decision-notices.steps.ts
e2e/features/step_definitions/issue-decision.steps.ts
e2e/helpers/dwp-office.ts

https://tools.hmcts.net/jira/browse/SSCS-8363
```
[ ] Yes
[ ] No
```

SSCS-8363: End2End testing ESA

---

e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/pages/case-details.page.ts

Fix ccd-tests

---

e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/pages/case-details.page.ts

Re-enable envelopeID test steps

---

e2e/features/data/incomplete-scanned-case.js
e2e/features/esa-decision-notices.feature
e2e/features/issue-decision.feature
e2e/features/issue-direction.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/issue-directions-notice.steps.ts
e2e/features/step_definitions/send-to-interloc.steps.ts
e2e/pages/any-ccd.page.ts

Tests for no-mrn-date bug

---

e2e/features/esa-decision-notices.feature

Untag ESA decision tests

---

e2e/features/esa-decision-notices.feature
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/esa-decision-notices.steps.ts

Sscs 8406 fix esa dn

---

e2e/features/step_definitions/esa-decision-notices.steps.ts

sscs 8406 failed === check

---

Jenkinsfile_nightly

Increased timeout to 2 hrs

---

e2e/features/step_definitions/action-further-evidence.steps.ts
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/urgent-hearing.feature

E2E tests for urgent hearing functionality

---

e2e/features/adjournment.feature
e2e/features/alternate-happy-path.feature
e2e/features/create-bulk-scanned-appeal.feature
e2e/features/createbundle.feature
e2e/features/data/sscs1peu-case.js
e2e/features/esa-decision-notices.feature
e2e/features/happy-path-user.feature
e2e/features/happy-path.feature
e2e/features/interloc-review.feature
e2e/features/issue-decision-award.feature
e2e/features/issue-decision.feature
e2e/features/issue-direction.feature
e2e/features/lapse-case.feature
e2e/features/reinstatement.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/urgent-hearing.feature
e2e/features/withdrawal.feature
e2e/pages/case-details.page.ts

Refactored tests for bulk-scan creation and added tests for SSCS1PEU form types

---

e2e/features/esa-decision-notices.feature
e2e/features/issue-decision.feature
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/esa-decision-notices.steps.ts
e2e/features/step_definitions/uc-decision-notices.steps.ts
e2e/features/uc-decision-notices.feature

https://tools.hmcts.net/jira/browse/SSCS-8481
UC tests
```
[ ] Yes
[x] No
```

sscs 8481 UC tests and updates to esa

---

e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/uc-decision-notices.steps.ts

https://tools.hmcts.net/jira/browse/SSCS-8481
```
[ ] Yes
[x] No
```

fixing style issues

---

e2e/features/step_definitions/dwp-upload-response.steps.ts

https://tools.hmcts.net/jira/browse/SSCS-8481
```
[ ] Yes
[x] No
```

style issue

---

e2e/features/adjournment.feature
e2e/features/alternate-happy-path.feature
e2e/features/createbundle.feature
e2e/features/happy-path-user.feature
e2e/features/interloc-review.feature

Updating old tests

---

e2e/features/happy-path.feature
e2e/features/issue-decision-award.feature

fixing tests

---

e2e/features/data/sscs1peu-case.js
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/uc-decision-notices.feature

Fix broken tests

---

e2e/features/uc-decision-notices.feature
e2e/pages/case-details.page.ts

Tests with updated dates

---

e2e/features/adjournment.feature

Disable adjournment tests due to ccd bug

---

e2e/pages/case-details.page.ts

Modify date

---

Jenkinsfile_nightly
e2e/pages/case-details.page.ts

… run at 5
```
[ ] Yes
[ ] No
```

Update date library methods in test and configure jenkins pipeline 

---

e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/ucb-and-subscription.steps.ts
e2e/features/update-phme.feature
e2e/pages/dwpresponse.page.ts

SSCS-8699: PHME and edited bundle test

---

e2e/features/step_definitions/ucb-and-subscription.steps.ts

yarn lint issue fix

---

e2e/features/step_definitions/uc-decision-notices.steps.ts
e2e/pages/issue-decision.page.ts

SSCS-8701 - Schedule6 page list ordering

SSCS-8701 - Schedule6 page list ordering

---

e2e/features/step_definitions/ucb-and-subscription.steps.ts
e2e/features/update-not-listable.feature

added test for appointee details

---

e2e/pages/case-details.page.ts

fixed the date issue

---

e2e/features/lapse-case.feature
e2e/features/step_definitions/action-further-evidence.steps.ts
e2e/pages/further-evidence.page.ts

Add tests to fill scanned date field

---

e2e/features/step_definitions/uc-decision-notices.steps.ts
e2e/features/uc-confidentiality-request.feature
e2e/pages/any-ccd.page.ts
e2e/pages/joint-party.page.ts

E2e test confidentiality req

---

e2e/features/withdrawal.feature

https://tools.hmcts.net/jira/browse/TA-545
- Withdrawal feature migrated to ExUI compatible.
```
[ ] Yes
[x] No
```

TA-545 Withdrawal feature migration

---

e2e/features/death-of-appellant.feature
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/ucb-and-subscription.steps.ts
e2e/pages/any-ccd.page.ts
e2e/pages/appointee.page.ts
e2e/service.conf.js

Sscs 8875 migrate death of appellant test to ExUI

---

e2e/features/step_definitions/action-further-evidence.steps.ts
e2e/features/step_definitions/authentication.steps.ts
e2e/features/urgent-hearing.feature

https://tools.hmcts.net/jira/browse/TA-546
- Migrating urgent-hearing.feature test to ExUI.
```
[ ] Yes
[x] No
```

TA-546 - Urgent hearing feature test refactored for ExUI

---

e2e/features/death-of-appellant.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/upload-response-with-further-info.feature
e2e/features/upload-response-without-further-info.feature
e2e/helpers/ccd.ts
e2e/pages/any-ccd-form.page.ts
e2e/pages/any-ccd.page.ts
e2e/pages/appointee.page.ts
e2e/pages/dwpresponse.page.ts
e2e/service.conf.js

Migrate pip and UC case digital journey tests to ExUI

---

e2e/features/json/pip_sya.json
e2e/features/json/uc_sya.json

Test json files

---

e2e/features/step_definitions/ucb-and-subscription.steps.ts
e2e/features/update-ucb.feature

https://tools.hmcts.net/jira/browse/TA-565
- Migrating update-ucb feature to ExUI
```
[ ] Yes
[x] No
```

Migrate update-ucb feature to ExUI

---

e2e/features/step_definitions/authentication.steps.ts
e2e/features/upload-response-with-further-info.feature
e2e/pages/case-details.page.ts
e2e/pages/response-reviewed.page.ts

Migrate dwp response tests to ExUI

---

e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/helpers/ccd.ts
e2e/pages/any-ccd.page.ts

fix lint issues on bkpatel81 branch

---

e2e/service.conf.js

Set proxy flag to false

---

e2e/features.parallel.conf.js
e2e/features/issue-decision.feature
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/issue-decision.steps.ts
e2e/pages/any-ccd.page.ts

https://tools.hmcts.net/jira/browse/TA-578
1. Dormant" state when decision is issued 
2. generate decision and award is about daily living or mobility
```
[ ] Yes
[x ] No
```

TA- 578 Issue Decision Scenarios

---

e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/esa-decision-notices.steps.ts
e2e/features/step_definitions/issue-decision.steps.ts
e2e/features/step_definitions/uc-decision-notices.steps.ts
e2e/features/step_definitions/ucb-and-subscription.steps.ts
e2e/features/uc-decision-notices.feature
e2e/pages/any-ccd-form.page.ts
e2e/pages/any-ccd.page.ts
e2e/pages/case-details.page.ts
e2e/pages/dwpresponse.page.ts
e2e/pages/issue-decision.page.ts

https://tools.hmcts.net/jira/browse/TA-573
- Migrating UC-decision-notices feature to ExUI
```
[ ] Yes
[x] No
```

TA-573 UC-decision-notices feature migration

---

e2e/features/issue-decision-award.feature
e2e/features/step_definitions/action-further-evidence.steps.ts
e2e/features/step_definitions/issue-decision.steps.ts
e2e/features/step_definitions/issue-directions-notice.steps.ts
e2e/pages/any-ccd.page.ts
e2e/pages/case-details.page.ts

https://tools.hmcts.net/jira/browse/TA-596
1.  Issue Decision Award Scenarios
```
[ ] Yes
[ x] No
```

TA 596 Issue Decision Award

---

e2e/features/esa-decision-notices.feature
e2e/features/json/esa_sya.json
e2e/helpers/ccd.ts

https://tools.hmcts.net/jira/browse/TA-600
1. Write ESA final decision WCA and refuse all
```
[ ] Yes
[X ] No
```

TA-600-Write ESA Final Decision And Refusal All E2E

---

e2e/features/esa-decision-notices.feature

https://tools.hmcts.net/jira/browse/TA-601
ESA final decision WCA and Support group, >= points for schedule 2, No Schedule 3, reg 35 YES and allow
```
[ ] Yes
[x ] No
```

TA 601 ESA final decision wca and support group e2 e

---

e2e/features/esa-decision-notices.feature

https://tools.hmcts.net/jira/browse/TA-606
1. ESA Final Decision Non WCA And Allow E2E
```
[ ] Yes
[ x] No
```

TA- 606-ESA Final Decision Non WCA And Allow E2E

---

e2e/features/esa-decision-notices.feature

https://tools.hmcts.net/jira/browse/TA-607
1. Write ESA Final Decision Non WCA And Refuse All E2E
```
[ ] Yes
[ x] No
```

TA-607-Write ESA Final Decision Non WCA And Refuse All E2E

---

e2e/features/esa-decision-notices-2.feature
e2e/features/esa-decision-notices.feature

https://tools.hmcts.net/jira/browse/TA-608
1. ESA Final Decision WCA And Refuse E2E
```
[ ] Yes
[x ] No
```

TA-608-ESA Final Decision WCA And Refuse E2E

---

e2e/features/step_definitions/ucb-and-subscription.steps.ts
e2e/features/update-not-listable.feature
e2e/pages/any-ccd.page.ts

https://tools.hmcts.net/jira/browse/TA-609
1. Update Not Listable E2E Scenarios
```
[ ] Yes
[x ] No
```

TA- 609 Updates Not Listable Scenarios

---

e2e/features/update-not-listable.feature

https://tools.hmcts.net/jira/browse/TA-611
1. Update not listable : No to direction full filled and interloc review to YES
```
[ ] Yes
[ x] No
```

TA-611-No to direction full filled and interloc review to YES

---

e2e/features/interloc-review.feature
e2e/features/issue-decision.feature
e2e/features/step_definitions/interloc-review.steps.ts

https://tools.hmcts.net/jira/browse/TA-614
1. Interloc Review E2E Scenarios
```
[ ] Yes
[x ] No
```

TA-614 -interloc review e2 e scenarios

---

e2e/features/reinstatement.feature
e2e/features/step_definitions/action-further-evidence.steps.ts

https://tools.hmcts.net/jira/browse/TA-615
1.Grant Reinstatement E2E
```
[ ] Yes
[ x] No
```

TA-615-Grant Reinstatement E2E

---

e2e/features/reinstatement.feature

https://tools.hmcts.net/jira/browse/TA-616
1. Refuse Reinstatement E2E
```
[ ] Yes
[ x] No
```

TA-616-Refuse Reinstatement E2E

---

e2e/features/step_definitions/ucb-and-subscription.steps.ts
e2e/features/update-subscriptions.feature
e2e/pages/any-ccd-form.page.ts

https://tools.hmcts.net/jira/browse/TA-617
1. Update Subscription E2E Scenarios
```
[ ] Yes
[ x] No
```

TA-617-Update Subscription E2E Scenarios

---

e2e/features/adjournment.feature
e2e/features/issue-decision.feature
e2e/features/step_definitions/adjournment.steps.ts
e2e/pages/adjournment.page.ts

https://tools.hmcts.net/jira/browse/TA-619
Adjournment E2E scenarios
```
[ ] Yes
[ x] No
```

TA-619-Adjournment E2E scenarios

---

e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/ucb-and-subscription.steps.ts
e2e/features/update-phme.feature

https://tools.hmcts.net/jira/browse/TA-618
Update PHME E2E
```
[ ] Yes
[ x] No
```

TA-618-Update PHME E2E

---

e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/esa-decision-notices.steps.ts
e2e/features/step_definitions/send-to-interloc.steps.ts
e2e/features/update-phme.feature
e2e/pages/any-ccd.page.ts
e2e/pages/appointee.page.ts

https://tools.hmcts.net/jira/browse/SSCS-9074
- n/a
```
[ ] Yes
[x] No
```

SSCS-9074 - Fix ccd-e2e failing tests

---

e2e/features/createbundle.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/update-phme.feature

https://tools.hmcts.net/jira/browse/TA-595
Create Bundle And Stitch Bundle Scenarios
```
[ ] Yes
[x ] No
```

TA-595 Create Bundle And Stitch Bundle Scenarios

---

e2e/pages/any-ccd.page.ts
e2e/pages/dwpresponse.page.ts

https://tools.hmcts.net/jira/browse/TA-622
Lint Issues fix
```
[ ] Yes
[ x] No
```

TA-622-Lint Issues fix

---

e2e/features/createbundle.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/esa-decision-notices.steps.ts
e2e/features/step_definitions/ucb-and-subscription.steps.ts
e2e/features/update-not-listable.feature
e2e/features/update-phme.feature
e2e/pages/any-ccd.page.ts
e2e/pages/case-details.page.ts

Fix ccd fixed tests 2

---

e2e/features/uc-decision-notices-2.feature
e2e/features/uc-decision-notices.feature

https://tools.hmcts.net/jira/browse/TA-621
1. Write UC final decision with manual upload
2. Write UC final decision non LCWA and allow
3. Write UC final decision non LCWA and refuse all
4. Write UC final decision LCWA and Not support group, <15 points for schedule 6, schedule 8 para 4 YES, Select Schedule 7 and allow
5. Write UC final decision LCWA and Not support group, <15 points for schedule 6, schedule 8 para 4 YES, No Schedule 7, schedule 9 para 4 YES,  and allow
```
[ ] Yes
[ x] No
```

TA-621-UC-E2E-Scenarios

---

e2e/features/update-phme.feature

Update text is test to match with new EM changes

---

e2e/features/step_definitions/interloc-review.steps.ts

Include new fields on tests for interloc journey

---

e2e/pages/case-details.page.ts

fix failures due to date

---

package.json

Fix nightly build

---

Jenkinsfile_nightly
package.json

https://tools.hmcts.net/jira/browse/TA-642
```
[ ] Yes
[x ] No
```

TA-642-EXUIFunctional Tests fix

---

e2e/features/reasonable-adjustments.feature
e2e/features/step_definitions/action-further-evidence.steps.ts
e2e/features/step_definitions/reasonable-adjustments.steps.ts
e2e/pages/any-ccd.page.ts

Add test coverage for reasonable adjustment events

---

e2e/cucumber.conf.js
e2e/features/esa-decision-notices-2.feature
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/uc-decision-notices-2.feature
e2e/pages/any-ccd.page.ts
package.json

https://tools.hmcts.net/jira/browse/TA-642
1. Set Protractor Default time 60s from 5mins
2. Admin Ready To List Event Fix
3. History Tab fix
4. Test Code improvements
```
[ ] Yes
[ x] No
```

TA-642-Admin Ready To List Event Fix

---

Jenkinsfile_nightly
e2e/pages/any-ccd.page.ts

https://tools.hmcts.net/jira/browse/TA-642
1. Fix for DWP state event
2. Enabled Cross browser tests
```
[ ] Yes
[ x] No
```

TA-642-Functional Test Fix

---

e2e/features/enhanced-confidentiality.feature
e2e/features/reinstatement.feature
e2e/features/step_definitions/action-further-evidence.steps.ts
e2e/features/step_definitions/any-ccd-page.steps.ts
e2e/features/step_definitions/enhanced-confidentiality.steps.ts
e2e/features/urgent-hearing.feature
e2e/pages/any-ccd.page.ts

https://tools.hmcts.net/jira/browse/SSCS-9373
- Added one happy path e2e Enhanced confidentiality test. 
```
[ ] Yes
[x] No
```

SSCS-9373 - Happy path EC test

---

e2e/features/step_definitions/process-audio-video-evidence.steps.ts
e2e/features/step_definitions/upload-document.steps.ts
e2e/features/upload-document-evidence.feature
e2e/pages/any-ccd.page.ts

tests for ccd events

---

e2e/features/reissue-further-evidence.feature
e2e/features/step_definitions/action-further-evidence.steps.ts

UI tests for reissue further evidence event

---

e2e/features/link-case.feature
e2e/features/step_definitions/link-case.steps.ts
e2e/pages/any-ccd.page.ts

link case UI tests

---

e2e/helpers/ccd.ts

Pointing set up step to use test endpoint

---

e2e/features/enhanced-confidentiality.feature
e2e/features/reissue-further-evidence.feature
e2e/features/step_definitions/action-further-evidence.steps.ts
e2e/features/step_definitions/enhanced-confidentiality.steps.ts
e2e/features/step_definitions/uc-decision-notices.steps.ts
e2e/features/uc-confidentiality-request.feature

Fix failing functional tests

---

e2e/features/uc-confidentiality-request.feature

fix minor typo

---

e2e/features/issue-decision-award.feature
e2e/features/pip-decision-notices.feature
e2e/features/step_definitions/issue-directions-notice.steps.ts

Add accidentally removed steps

---

e2e/features/hearing-recording.feature
e2e/features/step_definitions/hearing-recording.steps.ts
e2e/pages/hearing-recording.page.ts

https://tools.hmcts.net/jira/browse/SSCS-9379
```
[ ] Yes
[ x] No
```

SSCS-9379:Hearing recording feature

---

e2e/features/uc-decision-notices.feature

Remove additional test checks

---

e2e/features/create-bulk-scanned-appeal.feature
e2e/features/issue-direction.feature
e2e/features/pip-decision-notices.feature
e2e/features/update-subscriptions.feature
e2e/features/upload-document-evidence.feature
e2e/features/upload-response-without-further-info.feature

https://tools.hmcts.net/jira/browse/SSCS-9626
added tags for preview
```
[ ] Yes
[x] No
```

sscs 9627 added tag for tests

---

package.json

SSCS-9626 - add target for preview functional

SSCS-9626 - add target for preview functional

---

e2e/features/create-bulk-scanned-appeal.feature
e2e/features/createbundle.feature

SSCS-9626 - Create bundle test for preview

SSCS-9626 - Create bundle test for preview

---

e2e/features/upload-document-evidence.feature

SSCS-9626 - Change the Upload document preview tag

SSCS-9626 - Change the Upload document preview tag

---

e2e/features/step_definitions/adjournment.steps.ts
e2e/pages/adjournment.page.ts

Add steps to enter venue id

---

e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/update-phme.feature
e2e/features/upload-response-without-further-info.feature

Tests to verify dwp collection

---

e2e/features/search-filter.feature
e2e/features/step_definitions/search-filter.steps.ts

Add tests for workbasket filter

---

e2e/features/step_definitions/any-ccd-page.steps.ts
e2e/features/step_definitions/bulk-scanning.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/upload-response-with-further-info.feature
e2e/features/upload-response-without-further-info.feature
e2e/pages/any-ccd-form.page.ts
e2e/pages/any-ccd.page.ts
e2e/pages/dwpresponse.page.ts
package.json
yarn.lock

tests for child support upload response journey

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/SSCS-9401
```
[ ] Yes
[ x] No
```

SSCS-9401:Parallel threads increased to run e2e tests

---

e2e/features/json/child_support_sya.json
e2e/features/step_definitions/child-support.steps.ts
e2e/features/update-other-party-data.feature
e2e/helpers/ccd.ts

SSCS-9810 - Update Other Party Data

SSCS-9810 - Update Other Party Data 

---

e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/other-party-subscription.steps.ts
e2e/features/update-other-party-subscriptions.feature

https://tools.hmcts.net/jira/browse/SSCS-9807
```
[ ] Yes
[ ] No
```

SSCS-9807: Child Support: e2e Tests - Subscription

---

e2e/features/step_definitions/adjournment.steps.ts
e2e/features/step_definitions/esa-decision-notices.steps.ts
e2e/features/step_definitions/issue-decision.steps.ts
e2e/features/step_definitions/search-filter.steps.ts
e2e/pages/any-ccd.page.ts
e2e/pages/dwpresponse.page.ts
e2e/pages/lapsecase.page.ts
e2e/pages/response-reviewed.page.ts

fix failing tests due to page load timeout

---

e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/uc-decision-notices.steps.ts

Add explicit waits for UC steps

---

e2e/features/hearing-recording.feature
e2e/features/step_definitions/hearing-recording.steps.ts
e2e/pages/any-ccd.page.ts
e2e/pages/hearing-recording.page.ts

Refactor hearing-recording tests

---

Jenkinsfile_nightly
e2e/features/step_definitions/action-further-evidence.steps.ts
e2e/features/step_definitions/uc-decision-notices.steps.ts

Fix failing tests

---

e2e/features/lapse-case.feature

Remove additional steps

---

e2e/features/lapse-case.feature

verify only page loads in cross browser tests

---

e2e/features/amend-elements-issues.feature
e2e/features/step_definitions/amend-elements-issues.steps.ts
e2e/pages/any-ccd-form.page.ts
e2e/pages/any-ccd.page.ts

https://tools.hmcts.net/jira/browse/SSCS-9398
```
[ ] Yes
[X] No
```

Finish tests for SSCS 9398

---

e2e/features/reissue-document.feature
e2e/features/step_definitions/reissue-document.steps.ts

https://tools.hmcts.net/jira/browse/SSCS-9396
```
[ ] Yes
[X] No
```

Created test for reissue document

---

e2e/features/step_definitions/reasonable-adjustments.steps.ts
e2e/features/update-other-party-reasonable-adjustments.feature

https://tools.hmcts.net/jira/browse/SSCS-9809
Creating a e2e test for Child Support Reasonable adjustment other party.
```
[ ] Yes
[x] No
```

SSCS-9809: Child Support e2e Tests - Reasonable adjustment - other party

---

e2e/features/provide-appointee-details.feature
e2e/features/step_definitions/provide-appointee-details.step.ts
e2e/features/step_definitions/provide-appointee-details.steps.ts

Add UI tests for "provideAppointeeDetails" event
https://tools.hmcts.net/jira/browse/SSCS-9399
```
[ ] Yes
[ ] No
```

SSCS-9399 CCD E2E tests - Add UI tests for "provideAppointeeDetails" event

---

e2e/features/step_definitions/ucb-and-subscription.steps.ts
e2e/features/update-phme.feature

Update test for new changes

---

e2e/features/issue-direction.feature
e2e/features/json/tax_credit_sya.json
e2e/features/step_definitions/child-support.steps.ts
e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/esa-decision-notices.steps.ts
e2e/features/tc-decision-notices.feature
e2e/features/update-other-party-data.feature
e2e/features/upload-response-with-further-info.feature
e2e/features/upload-response-without-further-info.feature
e2e/pages/any-ccd.page.ts

SSCS5 Automation Coverage scripts

---

e2e/features/tc-decision-notices.feature
e2e/features/update-other-party-data.feature
e2e/features/upload-response-with-further-info.feature

SSCS5 scripts Refactor

---

e2e/features/step_definitions/dwp-upload-response.steps.ts
e2e/features/step_definitions/esa-decision-notices.steps.ts

build failure fix

---

e2e/pages/dwpresponse.page.ts

Add presenting officer tests

---

e2e/features/case-access-management.feature

Added WA fields tab test
```
[ ] Yes
[*] No
```

Added WA fields

---

e2e/features/step_definitions/issue-directions-notice.steps.ts

Fix issue-directions-notice.steps

---

Jenkinsfile_CNP
Jenkinsfile_nightly
config/custom-environment-variables.json
e2e/features.crossbrowser.conf.ts

Add retries

---

package.json

Enable e2e tests temporarily

---

package.json

Enable e2e tests

---

e2e/features/createbundle.feature
e2e/features/death-of-appellant.feature
e2e/features/error-message.feature
e2e/features/hearing-recording.feature
e2e/features/issue-direction.feature
e2e/features/lapse-case.feature
e2e/features/link-case.feature
e2e/features/provide-appointee-details.feature
e2e/features/reinstatement.feature
e2e/features/request-time-extension.feature
e2e/features/update-phme.feature
e2e/features/update-subscriptions.feature
e2e/features/update-ucb.feature
e2e/features/upload-response-with-further-info.feature
e2e/features/upload-response-without-further-info.feature
e2e/features/urgent-hearing.feature
e2e/features/withdrawal.feature

Remove playwright migrated tests from protractor test suite

---

e2e/features/schedule-listing-amend-hearing.feature
e2e/features/schedule-listing-create-hearing.feature

- https://tools.hmcts.net/jira/browse/SSCSCI-831
- delay hearing window start date from 28 to 31 days

SSCSCI-831: change hearingWindowStartDate 28to31
